#!/usr/bin/env bash

echo "GIT pre-push : Running unit tests...."
output=$(node_modules/.bin/jest)

if [[ $? != 0 ]]; then
    echo "$output"
    echo -e "\e[31m GIT PUSH ABORTED - test(s) failed \e[0m"
    echo "......................"
    exit 1
fi

echo "$output"
echo -e "\e[32m Pre-push unit test run passed \e[0m"
echo "..............."
exit 0

